
Search
Time
Deployment
Source
Log
2025-04-04 19:13:48.91
3ade0d32
System
starting up user application
2025-04-04 19:13:57.95
3ade0d32
User
Le ticket 1 a été renommé en 'Correction Interface'.
2025-04-04 19:13:57.95
3ade0d32
User
Charlie a été ajouté au ticket 1.
2025-04-04 19:13:57.95
3ade0d32
User
Alice a été retiré du ticket 1.
2025-04-04 19:13:57.95
3ade0d32
User
* Serving Flask app 'keep_alive'
2025-04-04 19:13:57.95
3ade0d32
User
* Debug mode: off
2025-04-04 19:13:57.96
3ade0d32
User
[2025-04-04 17:13:57] [INFO ] discord.client: logging in using static token
2025-04-04 19:13:57.96
3ade0d32
User
Traceback (most recent call last):
2025-04-04 19:13:57.96
3ade0d32
User
File "/home/runner/workspace/main.py", line 937, in
2025-04-04 19:13:57.96
3ade0d32
User
bot.run(TOKEN)
2025-04-04 19:13:57.96
3ade0d32
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/discord/client.py", line 906, in run
2025-04-04 19:13:57.97
3ade0d32
User
asyncio.run(runner())
2025-04-04 19:13:57.97
3ade0d32
User
File "/nix/store/nb21sc3npfc8gvazwnrjxpvb5d48jysx-python3-3.12.7/lib/python3.12/asyncio/runners.py", line 194, in run
2025-04-04 19:13:57.97
3ade0d32
User
return runner.run(main)
2025-04-04 19:13:57.97
3ade0d32
User
^^^^^^^^^^^^^^^^
2025-04-04 19:13:57.97
3ade0d32
User
File "/nix/store/nb21sc3npfc8gvazwnrjxpvb5d48jysx-python3-3.12.7/lib/python3.12/asyncio/runners.py", line 118, in run
2025-04-04 19:13:57.97
3ade0d32
User
return self._loop.run_until_complete(task)
2025-04-04 19:13:57.97
3ade0d32
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-04-04 19:13:57.97
3ade0d32
User
File "/nix/store/nb21sc3npfc8gvazwnrjxpvb5d48jysx-python3-3.12.7/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
2025-04-04 19:13:57.97
3ade0d32
User
return future.result()
2025-04-04 19:13:57.97
3ade0d32
User
^^^^^^^^^^^^^^^
2025-04-04 19:13:57.97
3ade0d32
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/discord/client.py", line 895, in runner
2025-04-04 19:13:57.97
3ade0d32
User
await self.start(token, reconnect=reconnect)
2025-04-04 19:13:57.97
3ade0d32
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/discord/client.py", line 823, in start
2025-04-04 19:13:57.97
3ade0d32
User
await self.login(token)
2025-04-04 19:13:57.97
3ade0d32
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/discord/client.py", line 649, in login
2025-04-04 19:13:57.97
3ade0d32
User
raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')
2025-04-04 19:13:57.97
3ade0d32
User
TypeError: expected token to be a str, received NoneType instead
2025-04-04 19:13:58.07
3ade0d32
System
forwarding local port 8080 to external port 80
2025-04-04 19:13:58.07
3ade0d32
User
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
